### PR TITLE
Update Info.plist.patch

### PR DESCRIPTION
**Pull request by ryanthara**
Add retina display support for OSX.

More information about the retina display can be found on [Apple Developer](https://developer.apple.com/library/content/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html) websites.

This will close this [issue](https://github.com/bardsoftware/ganttproject/issues/1108).

### CODE REVIEW

**Comment by ryanthara** [comment]
Hello Dmitry

Appreciate. It is working here on my MBP and shows the high resolution.

**Comment by dbarashev** [comment]
Hi,
this base branch change is not exactly what I meant.

I meant that you do in your local repository
```
git checkout BRANCH_2_7_X
# add your changes
git commit -a
git push origin BRANCH_2_7_X
```

and then create a pull request where base is `bardsoftware:BRANCH_2_7_X` and from is `ryanthara:BRANCH_2_7_X`

However, if you feel that it is too much for a one line change and don't care about your activity history ;) then I can add it appropriately myself.

**Comment by ryanthara** [comment]
Hi,

I try to do it the way you want. Everything ok?

**Comment by dbarashev** [comment]
I have commmited this change myself. You can download the build with this change applied from Dropbox: https://www.dropbox.com/sh/0gwuayq6vg0kyss/AAApogLPlvpg0lY9JltS-3sZa?dl=0 (there is zipped GanttProject.app)

**Comment by ryanthara** [comment]
Your implementation doesn't work. The <key>NSHighResolutionCapable</key><true/> is not on the right position and therefore the version on the dropbox doesn't start in retina mode. Although the window opens on the bottom left corner in minimised view. :-/

**Comment by dbarashev** [comment]
I guess this PR is obsolete as of 2024

**Pull request closed without merging**
