### PR TITLE
Gh 1699 gradle common ganttproject

### PR DESCRIPTION
**Pull request by WorkingDevel**
Moving `/src/` and `/resources/` into `src/main/(java|resources)` to fit gradle configuration-by-convention

The first 3 commits are from https://github.com/bardsoftware/ganttproject/pull/1791

### CODE REVIEW

**Comment by dbarashev** [comment]
Out of curiosity, does it bring any benefits, except that it now follows the conventions? I see the drawback: some tools are having troubles with the change history of each particular filet.

Here is the output of git log in your branch:
```
git log ganttproject/src/main/java/net/sourceforge/ganttproject/GanttProject.java
commit 123634e6b7f18779672ed31934c22d636492678a
Author: Christoph Graupner <ch.graupner@workingdeveloper.net>
Date:   Fri Oct 16 13:55:25 2020 +0200

    GH-1699 common gradle project structure for ganttproject
```

How it looks in GitHub interface:

image


Other issues:

Chart styles seem to be lost in the compiled distro (run `gradle runapp`)
image


Calendars are lost (there is none and custom in the dropdown.
These issues surely can be fixed, but what are the benefits of spending time on fixing them?

**Comment by WorkingDevel** [comment]
I think there are especially benefits for new-to-this-project developers:

* through knowledge of common gradle/maven project structure they need less time to understand the project structure
    * you don't need to take a look at the sub projects gradle file to get the resources and source dirs (that's also why I try to remove unused files as they lead a new developer into wasting time to find out what these files are there for)
* gradle plugins/bash scripts/ci tools you will find and add (via google, stackoverflow, ...) in the future are most likely configured by default for a gradle/maven layout, so you don't need to configure them for the custom structure
* there is already a subproject `biz.ganttproject.mxgraph` that has the gradle layout and it's different from the others. At least having a unified structure (gradle or not) for all subproject could make the dev's life easier as you don't need to pay attention for different layouts (e.g. if you use shell expansion in a script with `*/src/main/resouces/`)


For the git history: unfortunately `git log` cuts the log at a renaming of a file, a `--follow` does show the whole history:

`git log --follow ganttproject/src/main/java/net/sourceforge/ganttproject/GanttProject.java`

```
commit 123634e6b7f18779672ed31934c22d636492678a (HEAD -> GH-1699-build, origin/GH-1699-gradle-common-ganttproject, GH-1699-gradle-common-ganttproject)
Author: Christoph Graupner <ch.graupner@workingdeveloper.net>
Date:   Fri Oct 16 13:55:25 2020 +0200

    GH-1699 common gradle project structure for ganttproject

commit 8d57b02da41ad628a6e5fb3189ad0c9f2c816156
Author: Dmitry Barashev <dbarashev@ganttproject.biz>
Date:   Fri Oct 2 19:37:21 2020 +0300

    App update checker:
    * Send User agent
    * Handle errors better
    * Moved code into Update.kt from RssFeedChecker

commit 5d4354960a543c33cbf03956ff236c3ebcef44fd
Author: Dmitry Barashev <dbarashev@ganttproject.biz>
Date:   Fri Sep 18 20:06:31 2020 +0300

    Show Cloud documents in the recent docs list. Not allows for opening them yet.
...
```
I will fix the missing things like styling and calendars if you still consider this PR could be accepted.

**Comment by dbarashev** [comment]
Okay. Can we please keep CSS files with JavaFX styles in the same folder with Kotlin code? I like when they sit next to each other in the project pane.

**Comment by WorkingDevel** [comment]
Closed in preference of #1794 as I did a rebase to the current master to apply request:

> Okay. Can we please keep CSS files with JavaFX styles in the same folder with Kotlin code? I like when they sit next to each other in the project pane.

**Pull request closed without merging**
