### PR TITLE
GH-1699 gradle project structure

### PR DESCRIPTION
**Pull request by WorkingDevel**
This is the rebased and fixed PR of #1792 .
 
Moving `/src/` and `/resources/` into `src/main/(java|resources)` to fit gradle configuration-by-convention.

The `*.css` arew now left side by side to the classes using them in the `src/main/java/**`.

### CODE REVIEW

**Comment by dbarashev** [comment]
Something is wrong with the stylesheets again
image

**Comment by WorkingDevel** [comment]
@dbarashev you are right. It was missing. Needed to reintegrate the adaption of resources path to get resources into to jar where is loaded from.

**Comment by dbarashev** [comment]
When launched with `gradle run`, it won't start at all

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Input stream must not be null
        at javafx.graphics/javafx.scene.image.Image.validateInputStream(Image.java:1117)
        at javafx.graphics/javafx.scene.image.Image.<init>(Image.java:701)
        at biz.ganttproject.app.SplashKt$showAsync$1.run(Splash.kt:41)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:834)
Oct 26, 2020 4:12:44 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: null
java.lang.ExceptionInInitializerError
        at net.sourceforge.ganttproject.gui.NotificationChannel.<clinit>(NotificationChannel.java:32)
        at net.sourceforge.ganttproject.gui.NotificationManagerImpl.getChannelButtons(NotificationManagerImpl.java:75)
        at net.sourceforge.ganttproject.gui.GanttStatusBar.setNotificationManager(GanttStatusBar.java:236)
        at net.sourceforge.ganttproject.UIFacadeImpl.<init>(UIFacadeImpl.java:165)
        at net.sourceforge.ganttproject.GanttProjectBase.<init>(GanttProjectBase.java:110)
        at net.sourceforge.ganttproject.GanttProject.<init>(GanttProject.java:186)
        at net.sourceforge.ganttproject.AppKt$startUiApp$2.run(App.kt:67)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
        at net.sourceforge.ganttproject.gui.UIUtil.<clinit>(UIUtil.java:90)
        ... 20 more

Oct 26, 2020 4:12:44 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: null
java.lang.ExceptionInInitializerError
        at net.sourceforge.ganttproject.gui.NotificationChannel.<clinit>(NotificationChannel.java:32)
        at net.sourceforge.ganttproject.gui.NotificationManagerImpl.getChannelButtons(NotificationManagerImpl.java:75)
        at net.sourceforge.ganttproject.gui.GanttStatusBar.setNotificationManager(GanttStatusBar.java:236)
        at net.sourceforge.ganttproject.UIFacadeImpl.<init>(UIFacadeImpl.java:165)
        at net.sourceforge.ganttproject.GanttProjectBase.<init>(GanttProjectBase.java:110)
        at net.sourceforge.ganttproject.GanttProject.<init>(GanttProject.java:186)
        at net.sourceforge.ganttproject.AppKt$startUiApp$2.run(App.kt:67)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
```

**Comment by WorkingDevel** [comment]
added back `compile files('src/main/resources/resources')` that I thought is not really needed as resources should be loaded via equinox/eclipsito runtime.

**Pull request merged**
